create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  division text not null,
  status text not null default 'Tetap',
  location text not null default 'Jakarta',
  salary numeric not null default 0,
  attendance text not null default 'Hadir',
  check_in text not null default '08:30',
  created_at timestamptz not null default now()
);

create table if not exists leave_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  days integer not null default 1,
  date_range text not null,
  status text not null default 'Menunggu',
  created_at timestamptz not null default now()
);

create table if not exists candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  stage text not null default 'Screening',
  created_at timestamptz not null default now()
);

alter table employees enable row level security;
alter table leave_requests enable row level security;
alter table candidates enable row level security;

create policy "Allow public HRIS reads" on employees for select using (true);
create policy "Allow public HRIS inserts" on employees for insert with check (true);
create policy "Allow public HRIS updates" on employees for update using (true) with check (true);

create policy "Allow public leave reads" on leave_requests for select using (true);
create policy "Allow public leave inserts" on leave_requests for insert with check (true);
create policy "Allow public leave updates" on leave_requests for update using (true) with check (true);

create policy "Allow public candidate reads" on candidates for select using (true);
create policy "Allow public candidate inserts" on candidates for insert with check (true);
create policy "Allow public candidate updates" on candidates for update using (true) with check (true);

insert into employees (name, role, division, status, location, salary, attendance, check_in) values
  ('Alya Prameswari', 'HR Business Partner', 'People Ops', 'Tetap', 'Jakarta', 14500000, 'Hadir', '08:11'),
  ('Bima Santoso', 'Backend Engineer', 'Engineering', 'Tetap', 'Bandung', 18000000, 'Hadir', '08:28'),
  ('Citra Lestari', 'Finance Analyst', 'Finance', 'Tetap', 'Jakarta', 12500000, 'Terlambat', '09:14'),
  ('Damar Wirawan', 'Product Manager', 'Product', 'Tetap', 'Remote', 20500000, 'Hadir', '08:03'),
  ('Eka Mahendra', 'Sales Executive', 'Sales', 'Kontrak', 'Jakarta', 9800000, 'Cuti', '-'),
  ('Farah Nabila', 'UX Designer', 'Product', 'Tetap', 'Bandung', 13750000, 'Hadir', '08:36'),
  ('Gilang Saputra', 'Customer Success', 'Operations', 'Kontrak', 'Remote', 9200000, 'Hadir', '08:22'),
  ('Hana Putri', 'Recruiter', 'People Ops', 'Tetap', 'Jakarta', 11200000, 'Izin', '-');

insert into leave_requests (name, type, days, date_range, status) values
  ('Eka Mahendra', 'Tahunan', 3, '20-22 Mei 2026', 'Menunggu'),
  ('Hana Putri', 'Izin keluarga', 1, '17 Mei 2026', 'Menunggu'),
  ('Bima Santoso', 'Tahunan', 2, '27-28 Mei 2026', 'Disetujui');

insert into candidates (name, role, stage) values
  ('Raka Aditya', 'Frontend Engineer', 'Screening'),
  ('Nisa Amalia', 'People Analyst', 'Interview'),
  ('Yoga Pratama', 'Account Executive', 'Offering'),
  ('Maya Renata', 'Data Analyst', 'Hired');
